import Link from 'next/link'
import { redirect } from 'next/navigation'
import type { Prisma, TaskPriority, TaskStatus } from '@prisma/client'
import Topbar from '@/components/Topbar'
import FilterSelect from '@/components/FilterSelect'
import { Card, Chip, EmptyState, Field, inputClass, selectClass } from '@/components/ui'
import { canWrite, contractScope, requireUser } from '@/lib/access'
import { formatDate, initials } from '@/lib/format'
import { prisma } from '@/lib/prisma'
import { writeAudit } from '@/lib/audit'
import { notify } from '@/lib/notifications'

export const dynamic = 'force-dynamic'
const STATUS: Record<TaskStatus, { label: string; tone: 'off' | 'brand' | 'ok' | 'danger' }> = { TODO: { label: 'Не начато', tone: 'off' }, IN_PROGRESS: { label: 'В работе', tone: 'brand' }, DONE: { label: 'Готово', tone: 'ok' }, CANCELLED: { label: 'Отменено', tone: 'danger' } }
const PRIORITY: Record<TaskPriority, { label: string; tone: 'off' | 'warn' | 'danger' }> = { LOW: { label: 'Низкий', tone: 'off' }, MEDIUM: { label: 'Средний', tone: 'warn' }, HIGH: { label: 'Высокий', tone: 'danger' }, CRITICAL: { label: 'Критичный', tone: 'danger' } }

export default async function TasksPage({ searchParams }: { searchParams: { contract?: string; assignee?: string; status?: string; priority?: string; mine?: string } }) {
	const user = await requireUser()
	const scope: Prisma.TaskWhereInput = user.role === 'ADMIN' ? {} : user.role === 'MANAGER' ? { OR: [{ assigneeId: user.id }, { creatorId: user.id }, { contract: { managerId: user.id } }] } : { assigneeId: user.id }
	const filters: Prisma.TaskWhereInput = { deletedAt: null, ...scope, ...(searchParams.contract ? { contractId: searchParams.contract } : {}), ...(searchParams.assignee ? { assigneeId: searchParams.assignee } : {}), ...(Object.keys(STATUS).includes(searchParams.status ?? '') ? { status: searchParams.status as TaskStatus } : {}), ...(Object.keys(PRIORITY).includes(searchParams.priority ?? '') ? { priority: searchParams.priority as TaskPriority } : {}), ...(searchParams.mine === '1' ? { assigneeId: user.id } : {}) }
	const [tasks, contracts, users] = await Promise.all([
		prisma.task.findMany({ where: filters, include: { contract: { select: { id: true, number: true, contractor: { select: { name: true } } } }, assignee: { select: { id: true, name: true } }, _count: { select: { comments: true } } }, orderBy: [{ status: 'asc' }, { dueDate: 'asc' }, { priority: 'desc' }] }),
		prisma.contract.findMany({ where: { deletedAt: null, ...contractScope(user) }, select: { id: true, number: true, contractor: { select: { name: true } }, _count: { select: { tasks: { where: { deletedAt: null, status: { notIn: ['DONE', 'CANCELLED'] } } } } } }, orderBy: { date: 'desc' }, take: 300 }),
		prisma.user.findMany({ where: { deletedAt: null, isActive: true }, select: { id: true, name: true }, orderBy: { name: 'asc' } }),
	])

	async function createTask(formData: FormData) {
		'use server'
		const acting = await requireUser(); if (!canWrite(acting)) redirect('/tasks')
		const title = String(formData.get('title') ?? '').trim(), assigneeId = String(formData.get('assigneeId') ?? ''), requestedContractId = String(formData.get('contractId') ?? '') || null, due = String(formData.get('dueDate') ?? ''), priority = String(formData.get('priority') ?? 'MEDIUM') as TaskPriority
		const [assignee, allowedContract] = await Promise.all([
			prisma.user.findFirst({ where: { id: assigneeId, deletedAt: null, isActive: true }, select: { id: true } }),
			requestedContractId ? prisma.contract.findFirst({ where: { id: requestedContractId, deletedAt: null, ...contractScope(acting) }, select: { id: true } }) : null,
		])
		if (!title || !assignee || (requestedContractId && !allowedContract) || !Object.keys(PRIORITY).includes(priority)) redirect('/tasks')
		const contractId = allowedContract?.id ?? null
		const created = await prisma.task.create({ data: { title, description: String(formData.get('description') ?? '').trim() || null, category: String(formData.get('category') ?? '').trim() || null, contractId, assigneeId, creatorId: acting.id, dueDate: due ? new Date(`${due}T12:00:00.000Z`) : null, priority }, select: { id: true } })
		await writeAudit({ userId: acting.id, action: 'CREATE', entityType: 'Task', entityId: created.id })
		await notify({ userId: assigneeId, type: 'ASSIGNMENT', title: 'Вам назначена задача', message: title, href: `/tasks/${created.id}`, dedupeKey: `task-assignment:${created.id}:${assigneeId}` })
		redirect(`/tasks/${created.id}`)
	}

	const openCount = tasks.filter((task) => !['DONE','CANCELLED'].includes(task.status)).length
	const overdueCount = tasks.filter((task) => task.dueDate && task.dueDate < new Date() && !['DONE','CANCELLED'].includes(task.status)).length
	const name = user.name ?? user.email ?? ''
	return <><Topbar crumbs={[{ label: 'Главная', href: '/' }, { label: 'Задачи' }]} userName={name.split(' ')[0]} initials={initials(name)} notifications={overdueCount} />
		<div className="workspace-content">
			<div className="mb-[16px] flex items-start gap-4"><div><h1 className="text-2xl font-bold">Задачи</h1><div className="mt-[4px] text-base text-muted">{openCount} в работе · {overdueCount} просрочено</div></div>{canWrite(user) && <details className="group ml-auto"><summary className="brand-gradient cursor-pointer list-none rounded-control px-4 py-2.5 text-base font-semibold text-white">+ Создать задачу</summary><Card className="task-quick-create-panel absolute right-[26px] z-20 mt-[8px] w-[520px] p-4 shadow-xl"><form action={createTask} className="flex flex-col gap-3"><Field label="Задача" required><input name="title" required className={inputClass} /></Field><Field label="Описание"><input name="description" className={inputClass} /></Field><div className="grid grid-cols-2 gap-2.5"><Field label="Договор"><select name="contractId" defaultValue={searchParams.contract ?? ''} className={selectClass}><option value="">Без договора</option>{contracts.map((c) => <option key={c.id} value={c.id}>№ {c.number} · {c.contractor.name}</option>)}</select></Field><Field label="Исполнитель"><select name="assigneeId" required defaultValue={user.id} className={selectClass}>{users.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Срок"><input type="date" name="dueDate" className={inputClass} /></Field><Field label="Приоритет"><select name="priority" defaultValue="MEDIUM" className={selectClass}>{Object.entries(PRIORITY).map(([key,value]) => <option key={key} value={key}>{value.label}</option>)}</select></Field></div><Field label="Раздел"><input name="category" className={inputClass} placeholder="Проектирование, площадка, исполняшка…" /></Field><button className="brand-gradient h-control rounded-tight text-base font-semibold text-white">Создать</button></form></Card></details>}</div>
			<div className="three-col-panel grid grid-cols-[250px_minmax(0,1fr)_250px] gap-3.5">
				<Card className="min-h-[620px]"><div className="border-b border-line px-4 py-3.5 text-base font-semibold">Дерево задач</div><div className="p-2"><Link href="/tasks?mine=1" className="mb-[4px] flex items-center justify-between rounded-tight px-2 py-2 text-sm hover:bg-raised"><span>Мои задачи</span><b>{tasks.filter((task) => task.assigneeId === user.id).length}</b></Link><div className="px-2 pb-1 pt-2.5 text-xs font-semibold uppercase tracking-wide text-faint">Договоры</div>{contracts.map((contract) => <Link key={contract.id} href={`/tasks?contract=${contract.id}`} className={`flex items-center justify-between rounded-tight px-2 py-2 text-sm hover:bg-raised ${searchParams.contract === contract.id ? 'bg-brand-soft font-semibold text-brand-ink' : ''}`}><span className="truncate">№ {contract.number}</span><span className="ml-2 text-faint">{contract._count.tasks}</span></Link>)}</div></Card>
				<Card className="three-col-panel-main min-h-[620px] overflow-hidden"><div className="flex items-center border-b border-line px-4 py-3.5"><div className="font-semibold">{searchParams.contract ? `Договор ${contracts.find((c) => c.id === searchParams.contract)?.number ?? ''}` : 'Все задачи'}</div><span className="ml-auto text-sm text-muted">{tasks.length}</span></div>{tasks.length === 0 ? <EmptyState text="Задач по выбранным условиям нет" /> : <div><div className="grid grid-cols-[minmax(180px,1fr)_78px_82px_78px] gap-3 border-b border-line-soft bg-raised px-4 py-2 text-xs font-semibold uppercase tracking-wide text-faint 2xl:grid-cols-[minmax(210px,1fr)_90px_90px_115px_90px]"><span>Задача</span><span>Срок</span><span>Приоритет</span><span className="hidden 2xl:block">Исполнитель</span><span>Статус</span></div>{tasks.map((task) => { const overdue = task.dueDate && task.dueDate < new Date() && !['DONE','CANCELLED'].includes(task.status); return <Link key={task.id} href={`/tasks/${task.id}`} className="grid grid-cols-[minmax(180px,1fr)_78px_82px_78px] items-center gap-3 border-b border-line-soft px-4 py-3 last:border-0 hover:bg-raised/60 2xl:grid-cols-[minmax(210px,1fr)_90px_90px_115px_90px]"><div className="min-w-0"><div className="truncate text-base font-semibold">{task.title}</div><div className="mt-[2px] truncate text-xs text-muted">{task.contract ? `Договор №${task.contract.number} · ${task.contract.contractor.name}` : task.category ?? 'Общая задача'} · {task.assignee.name}{task._count.comments ? ` · 💬 ${task._count.comments}` : ''}</div></div><span className={`text-xs ${overdue ? 'font-semibold text-danger' : 'text-muted'}`}>{formatDate(task.dueDate)}</span><Chip tone={PRIORITY[task.priority].tone}>{PRIORITY[task.priority].label}</Chip><span className="hidden truncate text-xs 2xl:block">{task.assignee.name}</span><Chip tone={STATUS[task.status].tone}>{STATUS[task.status].label}</Chip></Link>})}</div>}</Card>
				<Card className="filter-panel h-fit"><div className="filter-panel-header border-b border-line px-4 py-3.5 text-base font-semibold">Фильтры</div><form method="get" className="filter-panel-form flex flex-col gap-3 p-4"><Field label="Исполнитель" labelClassName="filter-field-label"><FilterSelect name="assignee" defaultValue={searchParams.assignee ?? ''} options={[{ value: '', label: 'Все исполнители' }, ...users.map((item) => ({ value: item.id, label: item.name }))]} /></Field><Field label="Статус" labelClassName="filter-field-label"><FilterSelect name="status" defaultValue={searchParams.status ?? ''} options={[{ value: '', label: 'Все статусы' }, ...Object.entries(STATUS).map(([key, value]) => ({ value: key, label: value.label }))]} /></Field><Field label="Приоритет" labelClassName="filter-field-label"><FilterSelect name="priority" defaultValue={searchParams.priority ?? ''} options={[{ value: '', label: 'Все приоритеты' }, ...Object.entries(PRIORITY).map(([key, value]) => ({ value: key, label: value.label }))]} /></Field>{searchParams.contract && <input type="hidden" name="contract" value={searchParams.contract} />}<button className="brand-gradient h-control rounded-tight text-sm font-semibold text-white">Применить</button><Link href="/tasks" className="text-center text-sm text-muted">Сбросить фильтры</Link></form></Card>
			</div>
		</div></>
}
