'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { Card, Field, inputClass, selectClass, textareaClass } from '@/components/ui'

type Crew = { name: string; days: string; rate: string }
type Cost = { category: 'EQUIPMENT' | 'MATERIAL' | 'OTHER'; name: string; payment: 'CASH' | 'CASHLESS'; quantity: string; unit: string; price: string }
const num = (value: string) => Number(value.replace(',', '.')) || 0
const money = (value: number) => new Intl.NumberFormat('ru-RU', { style: 'currency', currency: 'RUB', maximumFractionDigits: 0 }).format(value)

export default function ReportForm({ action, siteId, today }: { action: (formData: FormData) => void | Promise<void>; siteId: string; today: string }) {
	const [crew, setCrew] = useState<Crew[]>([{ name: '', days: '1', rate: '0' }])
	const [costs, setCosts] = useState<Cost[]>([{ category: 'EQUIPMENT', name: '', payment: 'CASHLESS', quantity: '1', unit: 'смена', price: '0' }])
	const crewTotal = useMemo(() => crew.reduce((sum, row) => sum + num(row.days) * num(row.rate), 0), [crew])
	const costTotals = useMemo(() => costs.reduce((sum, row) => ({ ...sum, [row.category]: sum[row.category] + num(row.quantity) * num(row.price) }), { EQUIPMENT: 0, MATERIAL: 0, OTHER: 0 }), [costs])
	const updateCrew = (index: number, key: keyof Crew, value: string) => setCrew((rows) => rows.map((row, i) => i === index ? { ...row, [key]: value } : row))
	const updateCost = (index: number, key: keyof Cost, value: string) => setCosts((rows) => rows.map((row, i) => i === index ? { ...row, [key]: value } : row))

	return <Card className="overflow-hidden border-brand/20 bg-[linear-gradient(145deg,color-mix(in_srgb,var(--brand-soft)_42%,var(--surface)),var(--surface)_34%)] p-[22px] shadow-[0_18px_42px_rgba(34,24,82,.10)]"><form action={action} className="flex flex-col gap-[18px]">
		<input type="hidden" name="crewJson" value={JSON.stringify(crew)} /><input type="hidden" name="costJson" value={JSON.stringify(costs)} />
		<div className="grid grid-cols-1 gap-[14px] md:grid-cols-2"><Field label="Направление" required><select name="direction" className={selectClass} defaultValue="KJ"><option value="KJ">Монтаж КЖ</option><option value="KM">Монтаж КМ</option></select></Field><Field label="Дата" required><input type="date" name="workDate" required defaultValue={today} className={inputClass} /></Field></div>
		<Field label="Этап работ" required><input name="stage" required className={inputClass} placeholder="Монтаж колонн, устройство фундамента…" /></Field>

		<section className="rounded-[14px] border border-line bg-surface/80 p-[14px] shadow-sm"><div className="mb-[9px] flex items-center justify-between"><div><h2 className="text-[14px] font-semibold">Состав бригады</h2><p className="text-[11.5px] text-muted">Зарплата считается: дни × ставка</p></div><button type="button" onClick={() => setCrew((rows) => [...rows, { name: '', days: '1', rate: '0' }])} className="rounded-[8px] border border-line px-[11px] py-[6px] text-[11.5px] font-semibold transition hover:border-brand/40 hover:bg-brand-soft">+ Сотрудник</button></div>
			<div className="overflow-x-auto rounded-[10px] border border-line"><table className="w-full min-w-[560px] text-[12px]"><thead><tr className="bg-raised text-left text-muted"><th className="p-[8px]">Имя</th><th className="p-[8px]">Дней</th><th className="p-[8px]">Ставка</th><th className="p-[8px] text-right">Итого</th><th></th></tr></thead><tbody>{crew.map((row, index) => <tr key={index} className="border-t border-line-soft"><td className="p-[6px]"><input value={row.name} onChange={(e) => updateCrew(index, 'name', e.target.value)} placeholder="ФИО" className={inputClass} /></td><td className="p-[6px]"><input value={row.days} onChange={(e) => updateCrew(index, 'days', e.target.value)} inputMode="decimal" className={inputClass} /></td><td className="p-[6px]"><input value={row.rate} onChange={(e) => updateCrew(index, 'rate', e.target.value)} inputMode="decimal" className={inputClass} /></td><td className="p-[8px] text-right font-semibold">{money(num(row.days) * num(row.rate))}</td><td className="p-[6px]"><button type="button" onClick={() => setCrew((rows) => rows.filter((_, i) => i !== index))} className="text-danger">×</button></td></tr>)}</tbody><tfoot><tr className="border-t border-line bg-raised"><td colSpan={3} className="p-[9px] font-semibold">Итого зарплата</td><td className="p-[9px] text-right font-bold text-brand-ink">{money(crewTotal)}</td><td></td></tr></tfoot></table></div>
		</section>

		<section className="rounded-[14px] border border-line bg-surface/80 p-[14px] shadow-sm"><div className="mb-[9px] flex items-center justify-between"><div><h2 className="text-[14px] font-semibold">Техника, материалы и прочее</h2><p className="text-[11.5px] text-muted">Сумма считается: количество × цена</p></div><button type="button" onClick={() => setCosts((rows) => [...rows, { category: 'MATERIAL', name: '', payment: 'CASHLESS', quantity: '1', unit: 'шт.', price: '0' }])} className="rounded-[8px] border border-line px-[11px] py-[6px] text-[11.5px] font-semibold transition hover:border-brand/40 hover:bg-brand-soft">+ Позиция</button></div>
			<div className="flex flex-col gap-[7px]">{costs.map((row, index) => <div key={index} className="grid grid-cols-2 gap-[7px] rounded-[10px] border border-line p-[9px] md:grid-cols-[130px_1fr_110px_90px_90px_120px_28px]"><select value={row.category} onChange={(e) => updateCost(index, 'category', e.target.value as Cost['category'])} className={selectClass}><option value="EQUIPMENT">Техника</option><option value="MATERIAL">Материал</option><option value="OTHER">Прочее</option></select><input value={row.name} onChange={(e) => updateCost(index, 'name', e.target.value)} placeholder="Наименование" className={inputClass} /><select value={row.payment} onChange={(e) => updateCost(index, 'payment', e.target.value as Cost['payment'])} className={selectClass}><option value="CASHLESS">Безнал</option><option value="CASH">Наличные</option></select><input value={row.quantity} onChange={(e) => updateCost(index, 'quantity', e.target.value)} inputMode="decimal" placeholder="Кол-во" className={inputClass} /><input value={row.unit} onChange={(e) => updateCost(index, 'unit', e.target.value)} placeholder="ед." className={inputClass} /><input value={row.price} onChange={(e) => updateCost(index, 'price', e.target.value)} inputMode="decimal" placeholder="Цена" className={inputClass} /><button type="button" onClick={() => setCosts((rows) => rows.filter((_, i) => i !== index))} className="text-danger">×</button></div>)}</div>
			<div className="mt-[9px] grid grid-cols-3 gap-[7px] text-center text-[11.5px]"><div className="rounded-[9px] bg-raised p-[8px]">Техника<br/><b>{money(costTotals.EQUIPMENT)}</b></div><div className="rounded-[9px] bg-raised p-[8px]">Материалы<br/><b>{money(costTotals.MATERIAL)}</b></div><div className="rounded-[9px] bg-raised p-[8px]">Прочее<br/><b>{money(costTotals.OTHER)}</b></div></div>
		</section>

		<Field label="Комментарий"><textarea name="comment" className={textareaClass} placeholder="Что выполнено, что мешало, важные детали" /></Field><label className="flex cursor-pointer items-start gap-3 rounded-[11px] border border-brand/20 bg-brand-soft/40 px-4 py-3 text-[12px]"><input type="checkbox" name="finishDirection" className="mt-0.5 h-4 w-4" /><span><b className="block text-ink">Монтаж этого направления завершён</b><span className="mt-0.5 block text-muted">После КЖ договор перейдёт на монтаж КМ. После КМ он закроется автоматически, только если исполнительная документация готова.</span></span></label><Field label="Фотоотчёт" hint="До 10 фотографий по 20 МБ"><input type="file" name="photos" accept="image/jpeg,image/png,image/webp,image/heic" multiple className="block w-full rounded-[10px] border border-dashed border-line bg-raised px-[13px] py-[18px] text-[12.5px] text-muted" /></Field>
		<div className="rounded-[11px] bg-brand/10 p-[13px] text-right text-[14px] font-bold text-brand-ink">Итого за день: {money(crewTotal + costTotals.EQUIPMENT + costTotals.MATERIAL + costTotals.OTHER)}</div>
		<div className="flex gap-[10px]"><button className="brand-gradient inline-flex h-[40px] items-center rounded-[10px] px-[18px] text-[13.5px] font-semibold text-white">Сохранить отчёт</button><Link href={`/sites/${siteId}`} className="inline-flex h-[40px] items-center rounded-[10px] border border-line px-[18px] text-[13.5px] font-semibold">Отмена</Link></div>
	</form></Card>
}
